#ifndef AIR_CONDITIONING_BOARD_H
#define AIR_CONDITIONING_BOARD_H

#define AIR_CONDITIONING_BOARD_INPUT_BUFFER_LENGTH 				30
#define AIR_CONDITIONING_BOARD_OUTPUT_BUFFER_LENGTH 			30

// In debug uart, we don't need to store several messages
#define AIR_CONDITIONING_BOARD_DEBUG_INPUT_BUFFER_LENGTH		20
#define AIR_CONDITIONING_BOARD_DEBUG_OUTPUT_BUFFER_LENGTH		AIR_CONDITIONING_BOARD_OUTPUT_BUFFER_LENGTH

#define AIR_CONDITIONING_BOARD_I2C_INPUT_BUFFER_LENGTH			AIR_CONDITIONING_BOARD_INPUT_BUFFER_LENGTH
#define AIR_CONDITIONING_BOARD_I2C_OUTPUT_BUFFER_LENGTH			AIR_CONDITIONING_BOARD_OUTPUT_BUFFER_LENGTH

#define AIR_CONDITIONING_BOARD_REQUEST_DRIVER_BUFFER_LENGTH 	AIR_CONDITIONING_BOARD_INPUT_BUFFER_LENGTH
#define AIR_CONDITIONING_BOARD_RESPONSE_DRIVER_BUFFER_LENGTH 	AIR_CONDITIONING_BOARD_OUTPUT_BUFFER_LENGTH

// Devices
#define AIR_CONDITIONING_BOARD_DEVICE_LENGTH					2

// Timer
#define AIR_CONDITIONING_BOARD_TIMER_LENGTH						1

#endif
