#ifndef BEACON_RECEIVER_BOARD_H
#define BEACON_RECEIVER_BOARD_H

/** Define the I2C address used by beacon receiver. */
#define BEACON_RECEIVER_I2C_ADDRESS 	0x58

// BUFFER SIZE

#define BEACON_RECEIVER_BOARD_NULL_BUFFER_LENGTH				2

#define	BEACON_RECEIVER_BOARD_ZIGBEE_INPUT_BUFFER_LENGTH 		60
#define	BEACON_RECEIVER_BOARD_ZIGBEE_OUTPUT_BUFFER_LENGTH 		60

#define	BEACON_RECEIVER_BOARD_INPUT_BUFFER_LENGTH 				20
#define	BEACON_RECEIVER_BOARD_OUTPUT_BUFFER_LENGTH 				20

#define	BEACON_RECEIVER_BOARD_DEBUG_INPUT_BUFFER_LENGTH 		BEACON_RECEIVER_BOARD_INPUT_BUFFER_LENGTH
#define	BEACON_RECEIVER_BOARD_DEBUG_OUTPUT_BUFFER_LENGTH 		BEACON_RECEIVER_BOARD_OUTPUT_BUFFER_LENGTH

#define	BEACON_RECEIVER_BOARD_I2C_INPUT_BUFFER_LENGTH 			BEACON_RECEIVER_BOARD_INPUT_BUFFER_LENGTH
#define	BEACON_RECEIVER_BOARD_I2C_OUTPUT_BUFFER_LENGTH 			BEACON_RECEIVER_BOARD_OUTPUT_BUFFER_LENGTH




#endif
