#ifndef GAMEBOARD_ELEMENT_2018_H
#define GAMEBOARD_ELEMENT_2018_H

#include "../../robot/gameboard/gameboardElementList.h"

// StartArea
#define GAME_BOARD_START_AREA_2018_WIDTH        650.0f
#define GAME_BOARD_START_AREA_2018_HEIGHT       360.0f
#define GAME_BOARD_START_AREA_2018_GREEN_Y        0.0f
#define GAME_BOARD_START_AREA_2018_ORANGE_Y    2640.0f

// Garbage
#define GAME_BOARD_GARBAGE_2018_X              1750.0f
#define GAME_BOARD_GARBAGE_2018_WIDTH           250.0f
#define GAME_BOARD_GARBAGE_2018_HEIGHT          606.0f
#define GAME_BOARD_GARBAGE_2018_ORANGE_Y        894.0f
#define GAME_BOARD_GARBAGE_2018_GREEN_Y        1500.0f

// Switch
#define GAME_BOARD_SWITCH_2018_X                  0.0f
#define GAME_BOARD_SWITCH_GREEN_2018_Y         1130.0f
#define GAME_BOARD_SWITCH_ORANGE_2018_Y        GAMEBOARD_HEIGHT_INTEGER - GAME_BOARD_SWITCH_GREEN_2018_Y

// Cubes
#define GAME_BOARD_CUBE_WIDTH                    50.0f
#define GAME_BOARD_CUBE_HEIGHT                   50.0f
#define GAME_BOARD_CUBE_LEFT_X                  540.0f
#define GAME_BOARD_CUBE_MIDDLE_X               1190.0f
#define GAME_BOARD_CUBE_RIGHT_X                1500.0f
#define GAME_BOARD_CUBE_LEFT_Y1                 850.0f
#define GAME_BOARD_CUBE_MIDDLE_Y1               300.0f
#define GAME_BOARD_CUBE_RIGHT_Y1               1100.0f
#define GAME_BOARD_CUBE_LEFT_Y2                GAMEBOARD_HEIGHT - GAME_BOARD_CUBE_LEFT_Y1 
#define GAME_BOARD_CUBE_MIDDLE_Y2              GAMEBOARD_HEIGHT - GAME_BOARD_CUBE_MIDDLE_Y1
#define GAME_BOARD_CUBE_RIGHT_Y2               GAMEBOARD_HEIGHT - GAME_BOARD_CUBE_RIGHT_Y1

// BUILDING ZONE
#define GAME_BOARD_BUILDING_AREA_WIDTH          180.0f
#define GAME_BOARD_BUILDING_GREEN_AREA_Y        400.0f
#define GAME_BOARD_BUILDING_AREA_HEIGHT         560.0f
#define GAME_BOARD_BUILDING_ORANGE_AREA_Y      2040.0f

// BEE LAUNCHING_AREA
#define GAME_BOARD_BEE_LAUNCHING_AREA_X        2000.0f
#define GAME_BOARD_BEE_LAUNCHING_GREEN_AREA_Y   200.0f
#define GAME_BOARD_BEE_LAUNCHING_ORANGE_AREA_Y   GAMEBOARD_HEIGHT - GAME_BOARD_BEE_LAUNCHING_GREEN_AREA_Y

// DISTRIBUTORS
#define GAME_BOARD_DISTRIBUTOR_1_X              840.0f
#define GAME_BOARD_DISTRIBUTOR_1_GREEN_Y          0.0f
#define GAME_BOARD_DISTRIBUTOR_1_ORANGE_Y       GAMEBOARD_HEIGHT - GAME_BOARD_DISTRIBUTOR_1_GREEN_Y
#define GAME_BOARD_DISTRIBUTOR_2_X              GAMEBOARD_WIDTH
#define GAME_BOARD_DISTRIBUTOR_2_GREEN_Y        610.0f
#define GAME_BOARD_DISTRIBUTOR_2_ORANGE_Y       GAMEBOARD_HEIGHT - GAME_BOARD_DISTRIBUTOR_2_GREEN_Y

/**
 * Add the 2018 Gameboard elementzs.
 */
void addGameBoardElements2018(GameBoardElementList* gameBoardElementList);

#endif
