#ifndef SCORE_2018_H
#define SCORE_2018_H

#define SCORE_POINT_2018_NO_POINT                               0

// Unicolor Distributor
#define SCORE_POINT_2018_DISTRIBUTOR_UNLOADED_POINT             10
#define SCORE_POINT_2018_CLEAN_BALL_POINT                        5


#define SCORE_POINT_2018_DISTRIBUTOR_UNICOLOR_BALL_COUNT         8

#define SCORE_POINT_2018_DISTRIBUTOR_UNICOLOR_COMPLETE_POINT (SCORE_POINT_2018_DISTRIBUTOR_UNLOADED_POINT + SCORE_POINT_2018_CLEAN_BALL_POINT * SCORE_POINT_2018_DISTRIBUTOR_UNICOLOR_BALL_COUNT)

// Dirty balls
#define SCORE_POINT_2018_DIRTY_BALL_POINT                      10
#define SCORE_POINT_2018_DISTRIBUTOR_MIXEDCOLOR_BALL_COUNT      4
#define SCORE_POINT_2018_GARBAGE_RELEASE_POINT                 (SCORE_POINT_2018_DIRTY_BALL_POINT * SCORE_POINT_2018_DISTRIBUTOR_MIXEDCOLOR_BALL_COUNT)

// Cubes
#define SCORE_POINT_2018_CUBE_FLOOR_1_POINT                     1
#define SCORE_POINT_2018_CUBE_FLOOR_2_POINT                     2
#define SCORE_POINT_2018_CUBE_FLOOR_3_POINT                     3
#define SCORE_POINT_2018_CUBE_FLOOR_4_POINT                     4
#define SCORE_POINT_2018_CUBE_FLOOR_5_POINT                     5

// Panel
#define SCORE_POINT_2018_PANEL_INSTALLED_POINT                  5
#define SCORE_POINT_2018_PANEL_ON_POINT                        25

// Flower
#define SCORE_POINT_2018_BEE_INSTALLED_POINT                    5
#define SCORE_POINT_2018_BEE_DESTROYED_POINT                   50

// BONUS
#define SCORE_POINT_2018_OUTSIDE_START_AREA                    10

#endif
