#ifndef STRATEGY_TOF_SENSOR_LIST_2018_H
#define STRATEGY_TOF_SENSOR_LIST_2018_H

#include "../../drivers/tof/tofList.h"

// TOF MANAGEMENT
#define BACK_RIGHT_SENSOR_INDEX          0
#define BACK_MIDDLE_SENSOR_INDEX         1
#define BACK_LEFT_SENSOR_INDEX           2

#define FRONT_RIGHT_SENSOR_INDEX         3
#define FRONT_MIDDLE_SENSOR_INDEX        4
#define FRONT_LEFT_SENSOR_INDEX          5

// ORIENTATION
#define BACK_RIGHT_SENSOR_ANGLE_DEGREE   -160.0f
#define BACK_MIDDLE_SENSOR_ANGLE_DEGREE  -180.0f
#define BACK_LEFT_SENSOR_ANGLE_DEGREE   -200.0f

#define FRONT_RIGHT_SENSOR_ANGLE_DEGREE   -20.0f
#define FRONT_MIDDLE_SENSOR_ANGLE_DEGREE  0.0f
#define FRONT_LEFT_SENSOR_ANGLE_DEGREE   20.0f

// THRESHOLD
#define BACK_RIGHT_SENSOR_DISTANCE_THRESHOLD    600
#define BACK_MIDDLE_SENSOR_DISTANCE_THRESHOLD   800
#define BACK_LEFT_SENSOR_DISTANCE_THRESHOLD     600

#define FRONT_RIGHT_SENSOR_DISTANCE_THRESHOLD   600
#define FRONT_MIDDLE_SENSOR_DISTANCE_THRESHOLD  800
#define FRONT_LEFT_SENSOR_DISTANCE_THRESHOLD    600

void setTofListOrientationAngle2018(TofSensorList* tofSensorList);

#endif
