#ifndef MECHANICAL_BOARD_32_1_H
#define MECHANICAL_BOARD_32_1_H

#define MECA_BOARD_32_1_NAME          "MECA BOARD 32/1"

// COMMON
#define MECA_BOARD_32_1_INPUT_BUFFER_LENGTH         100
#define MECA_BOARD_32_1_OUTPUT_BUFFER_LENGTH        100

#define MECA_BOARD_32_1_I2C_INPUT_BUFFER_LENGTH        MECA_BOARD_32_1_INPUT_BUFFER_LENGTH
#define MECA_BOARD_32_1_I2C_OUTPUT_BUFFER_LENGTH       MECA_BOARD_32_1_OUTPUT_BUFFER_LENGTH

#define MECA_BOARD_32_1_I2C_DEBUG_MASTER_IN_BUFFER_LENGTH      MECA_BOARD_32_1_INPUT_BUFFER_LENGTH
#define MECA_BOARD_32_1_I2C_DEBUG_MASTER_OUT_BUFFER_LENGTH     MECA_BOARD_32_1_OUTPUT_BUFFER_LENGTH

// IO Expander
#define MECA_BOARD_32_1_IO_EXPANDER_LIST_LENGTH                1
#define MECA_BOARD_32_1_IO_EXPANDER_LAUNCHER_INDEX             0

// I2C
#define MECA_BOARD_32_1_I2C_BUS_LIST_LENGTH                    2
#define MECA_BOARD_32_1_I2C_BUS_CONNECTION_LIST_LENGTH         10
#define MECA_BOARD_32_1_I2C_MASTER_PORT                 I2C_BUS_PORT_4

// LOGS
#define MECA_BOARD_32_1_LOG_HANDLER_LIST_LENGTH   2

// TIMER
#define MECA_BOARD_32_1_TIMER_LENGTH        5

// DEVICE
#define MECA_BOARD_32_1_DEVICE_LENGTH       10

// UART
// How serial many ports are available on MECA_BOARD_32_1
#define MECA_BOARD_32_1_SERIAL_LINK_LIST_LENGTH 3
#define MECA_BOARD_32_1_SERIAL_PORT_STANDARD      SERIAL_PORT_2
#define MECA_BOARD_32_1_SERIAL_PORT_DEBUG         SERIAL_PORT_5


#define MECA_BOARD_32_1_STANDARD_INPUT_BUFFER_LENGTH    MECA_BOARD_32_1_INPUT_BUFFER_LENGTH
#define MECA_BOARD_32_1_STANDARD_OUTPUT_BUFFER_LENGTH   MECA_BOARD_32_1_OUTPUT_BUFFER_LENGTH

#define MECA_BOARD_32_1_DEBUG_INPUT_BUFFER_LENGTH       MECA_BOARD_32_1_INPUT_BUFFER_LENGTH
#define MECA_BOARD_32_1_DEBUG_OUTPUT_BUFFER_LENGTH      MECA_BOARD_32_1_OUTPUT_BUFFER_LENGTH

#endif
