#ifndef GAMEBOARD_ELEMENT_2019_H
#define GAMEBOARD_ELEMENT_2019_H

#include "../../robot/gameboard/gameboardElementList.h"

// PERIODIC TABLE -> REDIUM
#define GAME_BOARD_PERIODIC_TABLE_REDIUM_X              300.0f
#define GAME_BOARD_PERIODIC_TABLE_REDIUM_Y                0.0f
#define GAME_BOARD_PERIODIC_TABLE_REDIUM_WIDTH          300.0f
#define GAME_BOARD_PERIODIC_TABLE_REDIUM_HEIGHT         450.0f

// PERIODIC TABLE -> GREENIUM
#define GAME_BOARD_PERIODIC_TABLE_GREENIUM_X            GAME_BOARD_PERIODIC_TABLE_REDIUM_X + GAME_BOARD_PERIODIC_TABLE_REDIUM_WIDTH
#define GAME_BOARD_PERIODIC_TABLE_GREENIUM_Y            GAME_BOARD_PERIODIC_TABLE_REDIUM_Y
#define GAME_BOARD_PERIODIC_TABLE_GREENIUM_WIDTH        GAME_BOARD_PERIODIC_TABLE_REDIUM_WIDTH
#define GAME_BOARD_PERIODIC_TABLE_GREENIUM_HEIGHT       GAME_BOARD_PERIODIC_TABLE_REDIUM_HEIGHT

// PERIODIC TABLE -> BLUEIUM
#define GAME_BOARD_PERIODIC_TABLE_BLUEIUM_X            GAME_BOARD_PERIODIC_TABLE_GREENIUM_X + GAME_BOARD_PERIODIC_TABLE_GREENIUM_WIDTH
#define GAME_BOARD_PERIODIC_TABLE_BLUEIUM_Y            GAME_BOARD_PERIODIC_TABLE_GREENIUM_Y
#define GAME_BOARD_PERIODIC_TABLE_BLUEIUM_WIDTH        GAME_BOARD_PERIODIC_TABLE_GREENIUM_WIDTH
#define GAME_BOARD_PERIODIC_TABLE_BLUEIUM_HEIGHT       GAME_BOARD_PERIODIC_TABLE_GREENIUM_HEIGHT

// CHAOS AREA
#define GAME_BOARD_CHAOS_AREA_X                        1050.0f
#define GAME_BOARD_CHAOS_AREA_Y                        1000.0f
#define GAME_BOARD_CHAOS_AREA_RADIUS                    150.0f

// WEIGHING MACHINE
// -> SEPARATOR
#define GAME_BOARD_WEIGHING_MACHINE_SEPARATOR_X        1400.0f
#define GAME_BOARD_WEIGHING_MACHINE_SEPARATOR_Y        1480.0f
#define GAME_BOARD_WEIGHING_MACHINE_SEPARATOR_WIDTH     600.0f
#define GAME_BOARD_WEIGHING_MACHINE_SEPARATOR_HEIGHT     40.0f

// -> SQUARE
#define GAME_BOARD_WEIGHING_MACHINE_RECTANGLE_X        1543.0f
#define GAME_BOARD_WEIGHING_MACHINE_RECTANGLE_Y        1240.0f
#define GAME_BOARD_WEIGHING_MACHINE_RECTANGLE_WIDTH     422.0f
#define GAME_BOARD_WEIGHING_MACHINE_RECTANGLE_HEIGHT    220.0f

// BIG DISTRIBUTOR
#define GAME_BOARD_BIG_DISTRIBUTOR_X                   1543.0f
#define GAME_BOARD_BIG_DISTRIBUTOR_Y                    450.0f
#define GAME_BOARD_BIG_DISTRIBUTOR_WIDTH                  7.0f
#define GAME_BOARD_BIG_DISTRIBUTOR_HEIGHT               600.0f

#define GAME_BOARD_SMALL_DISTRIBUTOR_X                 2000.0f
#define GAME_BOARD_SMALL_DISTRIBUTOR_Y                   75.0f
#define GAME_BOARD_SMALL_DISTRIBUTOR_WIDTH                7.0f
#define GAME_BOARD_SMALL_DISTRIBUTOR_HEIGHT             300.0f

// ELEMENTS
#define GAME_BOARD_PUCK_RADIUS                           38.0f
#define GAME_BOARD_PUCK_RED_PERIODIC_TABLE_X            450.0f
#define GAME_BOARD_PUCK_RED_PERIODIC_TABLE_Y            500.0f
#define GAME_BOARD_PUCK_GREEN_PERIODIC_TABLE_X          750.0f
#define GAME_BOARD_PUCK_GREEN_PERIODIC_TABLE_Y          500.0f
#define GAME_BOARD_PUCK_BLUE_PERIODIC_TABLE_X          1050.0f
#define GAME_BOARD_PUCK_BLUE_PERIODIC_TABLE_Y           500.0f

// ACCELERATOR
#define GAME_BOARD_ACCELERATOR_X                          0.0f
#define GAME_BOARD_ACCELERATOR_Y                       1300.0f
#define GAME_BOARD_ACCELERATOR_WIDTH                     40.0f
#define GAME_BOARD_ACCELERATOR_HEIGHT                    80.0f


// GOLDENIUM
#define GAME_BOARD_GOLDENIUM_X                            0.0f
// TODO : To check !
#define GAME_BOARD_GOLDENIUM_Y                          735.0f
#define GAME_BOARD_GOLDENIUM_WIDTH                       40.0f
#define GAME_BOARD_GOLDENIUM_HEIGHT                      80.0f

/**
 * Add the 2019 Gameboard elementzs.
 */
void addGameBoardElements2019(GameBoardElementList* gameBoardElementList);

#endif
