#ifndef GAMEBOARD_ELEMENT_2019_H
#define GAMEBOARD_ELEMENT_2019_H

#include "../../robot/gameboard/gameboardElementList.h"

// PERIODIC TABLE -> REDIUM
#define GAME_BOARD_PERIODIC_TABLE_REDIUM_X            600.0f
#define GAME_BOARD_PERIODIC_TABLE_REDIUM_Y            0.0f
#define GAME_BOARD_PERIODIC_TABLE_REDIUM_WIDTH        300.0f
#define GAME_BOARD_PERIODIC_TABLE_REDIUM_HEIGHT       450.0f

// PERIODIC TABLE -> GREENIUM
#define GAME_BOARD_PERIODIC_TABLE_GREENIUM_X            GAME_BOARD_PERIODIC_TABLE_REDIUM_X + GAME_BOARD_PERIODIC_TABLE_REDIUM_WIDTH
#define GAME_BOARD_PERIODIC_TABLE_GREENIUM_Y            GAME_BOARD_PERIODIC_TABLE_REDIUM_Y
#define GAME_BOARD_PERIODIC_TABLE_GREENIUM_WIDTH        GAME_BOARD_PERIODIC_TABLE_REDIUM_WIDTH
#define GAME_BOARD_PERIODIC_TABLE_GREENIUM_HEIGHT       GAME_BOARD_PERIODIC_TABLE_REDIUM_HEIGHT

// PERIODIC TABLE -> BLUEIUM
#define GAME_BOARD_PERIODIC_TABLE_BLUEIUM_X            GAME_BOARD_PERIODIC_TABLE_GREENIUM_X + GAME_BOARD_PERIODIC_TABLE_GREENIUM_WIDTH
#define GAME_BOARD_PERIODIC_TABLE_BLUEIUM_Y            GAME_BOARD_PERIODIC_TABLE_GREENIUM_Y
#define GAME_BOARD_PERIODIC_TABLE_BLUEIUM_WIDTH        GAME_BOARD_PERIODIC_TABLE_GREENIUM_WIDTH
#define GAME_BOARD_PERIODIC_TABLE_BLUEIUM_HEIGHT       GAME_BOARD_PERIODIC_TABLE_GREENIUM_HEIGHT

// CHAOS AREA
#define GAME_BOARD_CHAOS_AREA_X                     1050.0f
#define GAME_BOARD_CHAOS_AREA_Y                     1000.0f
#define GAME_BOARD_CHAOS_AREA_RADIUS                150.0f


/**
 * Add the 2019 Gameboard elementzs.
 */
void addGameBoardElements2019(GameBoardElementList* gameBoardElementList);

#endif
