#ifndef MECHANICAL_BOARD_2_H
#define MECHANICAL_BOARD_2_H

#include <p30fxxxx.h>

/** Define the I2C address used by motorBoard. */
#define MECHANICAL_BOARD_2_I2C_ADDRESS 	0x54

#define PIN_SWITCH_LIFT_BOTTOM			PORTBbits.RB12

#define MECA_BOARD_2_INPUT_BUFFER_LENGTH 		10
#define MECA_BOARD_2_OUTPUT_BUFFER_LENGTH 		4

#define MECA_BOARD_2_DEBUG_INPUT_BUFFER_LENGTH		MECA_BOARD_2_INPUT_BUFFER_LENGTH
#define MECA_BOARD_2_DEBUG_OUTPUT_BUFFER_LENGTH		MECA_BOARD_2_OUTPUT_BUFFER_LENGTH

#define MECA_BOARD_2_I2C_INPUT_BUFFER_LENGTH		MECA_BOARD_2_INPUT_BUFFER_LENGTH
#define MECA_BOARD_2_I2C_OUTPUT_BUFFER_LENGTH		MECA_BOARD_2_OUTPUT_BUFFER_LENGTH



#endif
