#ifndef MECHANICAL_BOARD_2_H
#define MECHANICAL_BOARD_2_H

#include "../../common/io/buffer.h"

/** Define the I2C address used by Mechanical Board 2. */
#define MECHANICAL_BOARD_2_I2C_ADDRESS     0x56

#define PIN_SWITCH_LIFT_BOTTOM            PORTBbits.RB12

#define MECA_BOARD_2_INPUT_BUFFER_LENGTH         20
#define MECA_BOARD_2_OUTPUT_BUFFER_LENGTH         20

#define MECA_BOARD_2_DEBUG_INPUT_BUFFER_LENGTH        MECA_BOARD_2_INPUT_BUFFER_LENGTH
#define MECA_BOARD_2_DEBUG_OUTPUT_BUFFER_LENGTH        MECA_BOARD_2_OUTPUT_BUFFER_LENGTH

#define MECA_BOARD_2_I2C_INPUT_BUFFER_LENGTH        MECA_BOARD_2_INPUT_BUFFER_LENGTH
#define MECA_BOARD_2_I2C_OUTPUT_BUFFER_LENGTH        MECA_BOARD_2_OUTPUT_BUFFER_LENGTH

// LOGS
#define MECA_BOARD_2_LOG_HANDLER_LIST_LENGTH   2

// DEVICES

#define MECHANICAL_BOARD_2_DEVICE_LENGTH        10

// TIMERS

#define MECHANICAL_BOARD_2_TIMER_LENGTH            2

// DRIVER

#define MECA_2_REQUEST_DRIVER_BUFFER_LENGTH                 20
#define MECA_2_RESPONSE_DRIVER_BUFFER_LENGTH                20

// DISPATCHER

#define MECHANICAL_BOARD_2_DRIVER_DATA_DISPATCHER_LIST_LENGTH   1

/**
 * Get the I2C Slave Output Buffer.
 */
Buffer* getMechanicalBoard2I2CSlaveOutputBuffer();

#endif
