#ifndef STRATEGY_BOARD_H
#define STRATEGY_BOARD_H

/** Define the I2C address used by strategy Board. */
#define STRATEGY_BOARD_I2C_ADDRESS 	0x5A

#define STRATEGY_BOARD_INPUT_BUFFER_LENGTH 				30
#define STRATEGY_BOARD_OUTPUT_BUFFER_LENGTH 			30

#define STRATEGY_BOARD_DEBUG_INPUT_BUFFER_LENGTH		STRATEGY_BOARD_INPUT_BUFFER_LENGTH
#define STRATEGY_BOARD_DEBUG_OUTPUT_BUFFER_LENGTH		STRATEGY_BOARD_OUTPUT_BUFFER_LENGTH

#define STRATEGY_BOARD_I2C_INPUT_BUFFER_LENGTH			STRATEGY_BOARD_INPUT_BUFFER_LENGTH
#define STRATEGY_BOARD_I2C_OUTPUT_BUFFER_LENGTH			STRATEGY_BOARD_OUTPUT_BUFFER_LENGTH

#define STRATEGY_BOARD_REQUEST_DRIVER_BUFFER_LENGTH 	STRATEGY_BOARD_INPUT_BUFFER_LENGTH
#define STRATEGY_BOARD_RESPONSE_DRIVER_BUFFER_LENGTH 	STRATEGY_BOARD_OUTPUT_BUFFER_LENGTH

// Devices
#define STRATEGY_BOARD_DEVICE_LENGTH					2

#endif
