#ifndef STRATEGY_BOARD_H
#define STRATEGY_BOARD_H

#include <p30fxxxx.h>

/** Define the I2C address used by strategy Board. */
#define STRATEGY_BOARD_I2C_ADDRESS 	0x5A

#define STRATEGY_BOARD_INPUT_BUFFER_LENGTH 			20
#define STRATEGY_BOARD_OUTPUT_BUFFER_LENGTH 		20

#define STRATEGY_BOARD_DEBUG_INPUT_BUFFER_LENGTH	STRATEGY_BOARD_INPUT_BUFFER_LENGTH
#define STRATEGY_BOARD_DEBUG_OUTPUT_BUFFER_LENGTH	STRATEGY_BOARD_OUTPUT_BUFFER_LENGTH

#define STRATEGY_BOARD_I2C_INPUT_BUFFER_LENGTH		STRATEGY_BOARD_INPUT_BUFFER_LENGTH
#define STRATEGY_BOARD_I2C_OUTPUT_BUFFER_LENGTH		STRATEGY_BOARD_OUTPUT_BUFFER_LENGTH

#endif
