#ifndef SMALL_ROBOT_PATH_2019_H
#define SMALL_ROBOT_PATH_2019_H


// Strategy 1 
// -> Small Robot

#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_COST                          1800.0f
#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_CP1                           800.0f
#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_CP2                           500.0f
#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_SPEED_FACTOR                  1.0f
#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_ACCELERATION_FACTOR           1.0f

#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_CENTERED_COST                 1200.0f
#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_CENTERED_CP1                  800.0f
#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_CENTERED_CP2                  200.0f
#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_CENTERED_SPEED_FACTOR         1.0f
#define SMALL_ROBOT_STARTAREA_TO_ACCELERATOR_CENTERED_ACCELERATION_FACTOR  1.0f

#define ACCELERATOR_CENTERED_TO_ACCELERATOR_COST                           800.0f
#define ACCELERATOR_CENTERED_TO_ACCELERATOR_CP1                            200.0f
#define ACCELERATOR_CENTERED_TO_ACCELERATOR_CP2                            200.0f
#define ACCELERATOR_CENTERED_TO_ACCELERATOR_SPEED_FACTOR                   1.0f
#define ACCELERATOR_CENTERED_TO_ACCELERATOR_ACCELERATION_FACTOR            1.0f

#define ACCELERATOR_TO_GOLDENIUM_COST                                      500.0f
#define ACCELERATOR_TO_GOLDENIUM_CP1                                       50.0f
#define ACCELERATOR_TO_GOLDENIUM_CP2                                       300.0f
#define ACCELERATOR_TO_GOLDENIUM_SPEED_FACTOR                              0.5f
#define ACCELERATOR_TO_GOLDENIUM_ACCELERATION_FACTOR                       0.5f

#define GOLDENIUM_TO_WEIGHING_MACHINE_FRONT_COST                           1500.0f
#define GOLDENIUM_TO_WEIGHING_MACHINE_FRONT_CP1                            -400.0f
#define GOLDENIUM_TO_WEIGHING_MACHINE_FRONT_CP2                            -200.0f
#define GOLDENIUM_TO_WEIGHING_MACHINE_FRONT_SPEED_FACTOR                   1.0f
#define GOLDENIUM_TO_WEIGHING_MACHINE_FRONT_ACCELERATION_FACTOR            1.0f

#define WEIGHING_MACHINE_FRONT_TO_WEIGHING_MACHINE_DROP_COST                200.0f
#define WEIGHING_MACHINE_FRONT_TO_WEIGHING_MACHINE_DROP_CP1                 80.0f
#define WEIGHING_MACHINE_FRONT_TO_WEIGHING_MACHINE_DROP_CP2                 80.0f
#define WEIGHING_MACHINE_FRONT_TO_WEIGHING_MACHINE_DROP_SPEED_FACTOR        0.5f
#define WEIGHING_MACHINE_FRONT_TO_WEIGHING_MACHINE_DROP_ACCELERATION_FACTOR 0.5f

// Weighing Machine_Drop -> Chaos Zone Small Robot
#define WEIGHING_MACHINE_DROP_TO_CHAOS_ZONE_SMALL_ROBOT_COST                400.0f
#define WEIGHING_MACHINE_DROP_TO_CHAOS_ZONE_SMALL_ROBOT_CP1                -300.0f
#define WEIGHING_MACHINE_DROP_TO_CHAOS_ZONE_SMALL_ROBOT_CP2                -200.0f
#define WEIGHING_MACHINE_DROP_TO_CHAOS_ZONE_SMALL_ROBOT_SPEED_FACTOR         0.5f
#define WEIGHING_MACHINE_DROP_TO_CHAOS_ZONE_SMALL_ROBOT_ACCELERATION_FACTOR  0.5f

// Chaos Zone Small Robot -> Weighing Machine_Drop
#define CHAOS_ZONE_SMALL_ROBOT_TO_WEIGHING_MACHINE_DROP_COST               WEIGHING_MACHINE_DROP_TO_CHAOS_ZONE_SMALL_ROBOT_COST
#define CHAOS_ZONE_SMALL_ROBOT_TO_WEIGHING_MACHINE_DROP_CP1                200.0f
#define CHAOS_ZONE_SMALL_ROBOT_TO_WEIGHING_MACHINE_DROP_CP2                300.0f
#define CHAOS_ZONE_SMALL_ROBOT_TO_WEIGHING_MACHINE_SPEED_FACTOR            WEIGHING_MACHINE_DROP_TO_CHAOS_ZONE_SMALL_ROBOT_SPEED_FACTOR
#define CHAOS_ZONE_SMALL_ROBOT_TO_WEIGHING_MACHINE_ACCELERATION_FACTOR     WEIGHING_MACHINE_DROP_TO_CHAOS_ZONE_SMALL_ROBOT_ACCELERATION_FACTOR

// Chaos Zone Small Robot -> Big Distributor Line 3
#define CHAOS_ZONE_SMALL_ROBOT_TO_BIG_DISTRIBUTOR_LINE3_COST               400.0f
#define CHAOS_ZONE_SMALL_ROBOT_TO_BIG_DISTRIBUTOR_LINE3_CP1                100.0f
#define CHAOS_ZONE_SMALL_ROBOT_TO_BIG_DISTRIBUTOR_LINE3_CP2                200.0f
#define CHAOS_ZONE_SMALL_ROBOT_TO_BIG_DISTRIBUTOR_LINE3_SPEED_FACTOR       0.5f
#define CHAOS_ZONE_SMALL_ROBOT_TO_BIG_DISTRIBUTOR_LINE3_ACCELERATION_FACTOR     0.5f

// Big Distributor Line 3 -> RediumGreeniumFrontDrop
#define BIG_DISTRIBUTOR_LINE_3_TO_REDIUM_GREENIUM_FRONT_DROP_COST          700.0f
#define BIG_DISTRIBUTOR_LINE_3_TO_REDIUM_GREENIUM_FRONT_DROP_CP1          -300.0f
#define BIG_DISTRIBUTOR_LINE_3_TO_REDIUM_GREENIUM_FRONT_DROP_CP2          -300.0f
#define BIG_DISTRIBUTOR_LINE_3_TO_REDIUM_GREENIUM_FRONT_SPEED_FACTOR         0.8f
#define BIG_DISTRIBUTOR_LINE_3_TO_REDIUM_GREENIUM_FRONT_ACCELERATOR_FACTOR   0.5f

// RediumGreeniumFrontDrop => RediumGreeniumDropZone
#define REDIUM_GREENIUM_FRONT_DROP_TO_REDIUM_GREENIUM_DROP_ZONE_COST       200.0f
#define REDIUM_GREENIUM_FRONT_DROP_TO_REDIUM_GREENIUM_DROP_ZONE_CP1         50.0f
#define REDIUM_GREENIUM_FRONT_DROP_TO_REDIUM_GREENIUM_DROP_ZONE_CP2         50.0f
#define REDIUM_GREENIUM_FRONT_DROP_TO_REDIUM_GREENIUM_DROP_ZONE_SPEED_FACTOR         0.8f
#define REDIUM_GREENIUM_FRONT_DROP_TO_REDIUM_GREENIUM_DROP_ZONE_ACCELERATOR_FACTOR   0.5f


// Weighing -> Small Distributor 1

#define WEIGHING_MACHINE_TO_BLUEIUM_RIGHT_COST                              600.0f
#define WEIGHING_MACHINE_TO_BLUEIUM_RIGHT_CP1                              -300.0f
#define WEIGHING_MACHINE_TO_BLUEIUM_RIGHT_CP2                              -100.0f
#define WEIGHING_MACHINE_TO_BLUEIUM_RIGHT_SPEED_FACTOR                      0.75f
#define WEIGHING_MACHINE_TO_BLUEIUM_RIGHT_ACCELERATION_FACTOR               0.75f

#define BLUEIUM_RIGHT_TO_SMALL_DISTRIBUTOR_LINE_1_COST                      300.0f
#define BLUEIUM_RIGHT_TO_SMALL_DISTRIBUTOR_LINE_1_CP1                       100.0f
#define BLUEIUM_RIGHT_TO_SMALL_DISTRIBUTOR_LINE_1_CP2                       100.0f
#define BLUEIUM_RIGHT_TO_SMALL_DISTRIBUTOR_LINE_1_SPEED_FACTOR               0.8f
#define BLUEIUM_RIGHT_TO_SMALL_DISTRIBUTOR_LINE_1_ACCELERATION_FACTOR        0.8f

// Small Distributor 1 -> Weighing

#define SMALL_DISTRIBUTOR_LINE_1_TO_BLUEIUM_RIGHT_COST                      300.0f
#define SMALL_DISTRIBUTOR_LINE_1_TO_BLUEIUM_RIGHT_CP1                      -200.0f
#define SMALL_DISTRIBUTOR_LINE_1_TO_BLUEIUM_RIGHT_CP2                      -100.0f
#define SMALL_DISTRIBUTOR_LINE_1_TO_BLUEIUM_RIGHT_SPEED_FACTOR               0.75f
#define SMALL_DISTRIBUTOR_LINE_1_TO_BLUEIUM_RIGHT_ACCELERATION_FACTOR        0.75f

#define BLUEIUM_RIGHT_TO_WEIGHING_MACHINE_COST                              600.0f
#define BLUEIUM_RIGHT_TO_WEIGHING_MACHINE_CP1                               100.0f
#define BLUEIUM_RIGHT_TO_WEIGHING_MACHINE_CP2                               300.0f
#define BLUEIUM_RIGHT_TO_WEIGHING_MACHINE_SPEED_FACTOR                      0.75f
#define BLUEIUM_RIGHT_TO_WEIGHING_MACHINE_ACCELERATION_FACTOR               0.75f

#endif
