// SENSOR TEMPERATURE
#ifndef LM75A_H
#define    LM75A_H

#define LM75A_READ_SENSOR_REGISTER              0x00
#define LM75A_CONFIGURATION_SENSOR_REGISTER     0x01
#define LM75A_HYSTERESIS_SENSOR_REGISTER        0x02
#define LM75A_OVER_TEMPERATURE_SENSOR_REGISTER   0x03

// Overtemp Shutdown output
//  0  OS active LOW
//  1  OS active HIGH
#define OS_POLARITY_LOW 0x00
#define OS_POLARITY_HIGH 0x04


#endif

