#ifndef LM75A_H
#define	LM75A_H

#define LM75A_READ_SENSOR_REGISTER              0x00
#define LM75A_CONFIGURATION_SENSOR_REGISTER     0x01
#define LM75A_HYSTERESIS_SENSOR_REGISTER        0x02
#define LM75A_OVERTEMPERATURE_SENSOR_REGISTER   0x03


#endif

