#ifndef DRIVER_DATA_DISPATCHER_LIST_TEST_H
#define DRIVER_DATA_DISPATCHER_LIST_TEST_H

void driverDataDispatcherListTestSuite(void);

void test_initDriverDataDispatcherList_should_fail_if_null_provided(void);

void test_initDriverDataDispatcherList_add_too_much_dispatchers(void);

void test_initDriverDataDispatcherList_find_dispatcher_by_transmit_mode(void);

#endif
