#ifndef BIG_ROBOT_PATH_2019_H
#define BIG_ROBOT_PATH_2019_H

// -> Big Robot : Start Area -> Big Distributor Line 1
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_COST             1200.0f
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_CP1              450.0f
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_CP2              250.0f
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_SPEED_FACTOR     0.8f
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_ACCELERATION_FACTOR  0.8f

// -> Big Robot : Start Area -> Chaos Zone Front
#define BIG_ROBOT_STARTAREA_TO_CHAOS_ZONE_FRONT_COST             1500.0f
#define BIG_ROBOT_STARTAREA_TO_CHAOS_ZONE_FRONT_CP1              550.0f
#define BIG_ROBOT_STARTAREA_TO_CHAOS_ZONE_FRONT_CP2              250.0f
#define BIG_ROBOT_STARTAREA_TO_CHAOS_ZONE_FRONT_SPEED_FACTOR     1.0f
#define BIG_ROBOT_STARTAREA_TO_CHAOS_ZONE_FRONT_ACCELERATION_FACTOR 1.0f

// Chaos Zone Front -> Redium Drop Zone
#define CHAOS_ZONE_FRONT_TO_REDIUM_DROP_ZONE_COST             900.0f
#define CHAOS_ZONE_FRONT_TO_REDIUM_DROP_ZONE_CP1              200.0f
#define CHAOS_ZONE_FRONT_TO_REDIUM_DROP_ZONE_CP2              200.0f
#define CHAOS_ZONE_FRONT_TO_REDIUM_DROP_ZONE_SPEED_FACTOR          1.0f
#define CHAOS_ZONE_FRONT_TO_REDIUM_DROP_ZONE_ACCELERATION_FACTOR   1.0f

// Redium Drop Zone -> Key Point 1
#define REDIUM_DROP_ZONE_TO_KEY_POINT_1_COST                  1000.0f
#define REDIUM_DROP_ZONE_TO_KEY_POINT_1_CP1                   -200.0f
#define REDIUM_DROP_ZONE_TO_KEY_POINT_1_CP2                   -200.0f
#define REDIUM_DROP_ZONE_TO_KEY_POINT_1_SPEED_FACTOR          1.0f
#define REDIUM_DROP_ZONE_TO_KEY_POINT_1_ACCELERATION_FACTOR   1.0f

// Redium Drop Zone -> Key Point 2
#define REDIUM_DROP_ZONE_TO_KEY_POINT_2_COST                   400.0f
#define REDIUM_DROP_ZONE_TO_KEY_POINT_2_CP1                   -200.0f
#define REDIUM_DROP_ZONE_TO_KEY_POINT_2_CP2                   -300.0f
#define REDIUM_DROP_ZONE_TO_KEY_POINT_2_SPEED_FACTOR          1.0f
#define REDIUM_DROP_ZONE_TO_KEY_POINT_2_ACCELERATION_FACTOR   1.0f

// Key Point 2 -> BigDistributor Line 1
#define KEY_POINT_2_TO_BIGDISTRIBUTOR_LINE_1_FRONT_COST                800.0f
#define KEY_POINT_2_TO_BIGDISTRIBUTOR_LINE_1_FRONT_CP1                 250.0f
#define KEY_POINT_2_TO_BIGDISTRIBUTOR_LINE_1_FRONT_CP2                 250.0f
#define KEY_POINT_2_TO_BIGDISTRIBUTOR_LINE_1_FRONT_SPEED_FACTOR        1.0f
#define KEY_POINT_2_TO_BIGDISTRIBUTOR_LINE_1_FRONT_ACCELERATION_FACTOR 1.0f

// Big Distributor Line 1 <-> Key Point 1
#define BIGDISTRIBUTOR_LINE1_FRONT_TO_KEY_POINT_1_COST                1000.0f
#define BIGDISTRIBUTOR_LINE1_FRONT_TO_KEY_POINT_1_CP1                 -600.0f
#define BIGDISTRIBUTOR_LINE1_FRONT_TO_KEY_POINT_1_CP2                 -250.0f
#define BIGDISTRIBUTOR_LINE1_FRONT_TO_KEY_POINT_1_SPEED_FACTOR        1.0f
#define BIGDISTRIBUTOR_LINE1_FRONT_TO_KEY_POINT_1_ACCELERATION_FACTOR 1.0f

// Key Point 1 <-> Drop Zone
#define KEY_POINT_1_TO_ACCELERATOR_DROP_COST                1000.0f
#define KEY_POINT_1_TO_ACCELERATOR_DROP_CP1                 250.0f
#define KEY_POINT_1_TO_ACCELERATOR_DROP_CP2                 350.0f
#define KEY_POINT_1_TO_ACCELERATOR_DROP_SPEED_FACTOR        1.0f
#define KEY_POINT_1_TO_ACCELERATOR_DROP_ACCELERATION_FACTOR 1.0f

// Drop Zone <-> Key Point 1
#define ACCELERATOR_DROP_TO_KEY_POINT_1_COST                KEY_POINT_1_TO_ACCELERATOR_DROP_COST
#define ACCELERATOR_DROP_TO_KEY_POINT_1_CP1                 -350.0f
#define ACCELERATOR_DROP_TO_KEY_POINT_1_CP2                 -250.0f
#define ACCELERATOR_DROP_TO_KEY_POINT_1_SPEED_FACTOR        1.0f
#define ACCELERATOR_DROP_TO_KEY_POINT_1_ACCELERATION_FACTOR 1.0f

// Key Point 1 <-> BigDistributor Line 2
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_2_FRONT_COST                1000.0f
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_2_FRONT_CP1                 250.0f
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_2_FRONT_CP2                 800.0f
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_2_FRONT_SPEED_FACTOR        1.0f
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_2_FRONT_ACCELERATION_FACTOR 1.0f

#define BIGDISTRIBUTOR_LINE2_FRONT_TO_KEY_POINT_1_COST                KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_2_FRONT_COST
#define BIGDISTRIBUTOR_LINE2_FRONT_TO_KEY_POINT_1_CP1                 -900.0f
#define BIGDISTRIBUTOR_LINE2_FRONT_TO_KEY_POINT_1_CP2                 -250.0f
#define BIGDISTRIBUTOR_LINE2_FRONT_TO_KEY_POINT_1_SPEED_FACTOR        1.0f
#define BIGDISTRIBUTOR_LINE2_FRONT_TO_KEY_POINT_1_ACCELERATION_FACTOR 1.0f

// Key Point 1 <-> BigDistributor Line 3
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_3_FRONT_COST                1000.0f
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_3_FRONT_CP1                 250.0f
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_3_FRONT_CP2                 200.0f
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_3_FRONT_SPEED_FACTOR        1.0f
#define KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_3_FRONT_ACCELERATION_FACTOR 1.0f

#define BIGDISTRIBUTOR_LINE_3_FRONT_TO_KEY_POINT_1_COST                KEY_POINT_1_TO_BIGDISTRIBUTOR_LINE_3_FRONT_COST
#define BIGDISTRIBUTOR_LINE_3_FRONT_TO_KEY_POINT_1_CP1                 -200.0f
#define BIGDISTRIBUTOR_LINE_3_FRONT_TO_KEY_POINT_1_CP2                 -250.0f
#define BIGDISTRIBUTOR_LINE_3_FRONT_TO_KEY_POINT_1_SPEED_FACTOR        1.0f
#define BIGDISTRIBUTOR_LINE_3_FRONT_TO_KEY_POINT_1_ACCELERATION_FACTOR 1.0f

#endif

