#ifndef BIG_ROBOT_PATH_2020_H
#define BIG_ROBOT_PATH_2020_H

// -> Big Robot : Start Area -> Big Distributor Line 1
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_COST                1200.0f
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_CP1                 450.0f
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_CP2                 250.0f
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_SPEED_FACTOR         0.8f
#define BIG_ROBOT_STARTAREA_TO_BIGDISTRIBUTOR_LINE_1_FRONT_ACCELERATION_FACTOR  0.8f

#endif

