#ifndef STRATEGY_2012_H
#define STRATEGY_2012_H

#include "../../robot/strategy/gameTarget.h"
#include "../../robot/match/teamColor.h"

#include "../../motion/simple/motion.h"


#define 	ANGLE_90			0x0384
#define		ANGLE_135			0x0546
#define		ANGLE_150			0x05DC
#define		ANGLE_180			0x0708
#define		ANGLE_NEG_90		0xFC7C
#define		ANGLE_NEG_110		0xFBB4

// LOCATIONS / TARGETS

// -> General Points
#define START_AREA				"startArea"
#define BULLION_1				"bullion1"
#define BOTTLE_1				"bottle1"
#define BOTTLE_2				"bottle2"
#define BOTTLE_2_FRONT			"bottle2Front"
#define CD_TAKE					"cdTake"
#define DROP_ZONE_1				"dropZone1"
#define FRONT_OF_MAP_LOCATION	"frontOfMapLocation"

// -> Bullion1
#define BULLION_RIGHT_1			"bullionRight1"
#define BULLION_RIGHT_2			"bullionRight2"
#define BULLION_LEFT_1			"bullionLeft1"
#define BULLION_LEFT_2			"bullionLeft2"

// -> Opponent CD
#define OPPONENT_CD				"opponentCD"
#define BULLION_MIDDLE_2		"bullionMiddle2"


// CONSTANTS

#define 	X_BOTTLE 			0x0730

#define 	X_LINTEL_LEFT		0x284

// Symetric
#define 	X_LINTEL_RIGHT 		2000 - X_LINTEL_LEFT

// COORDINATES
#define START_AREA_X					170
#define START_AREA_Y					170

#define BULLION_1_X						0x0370
#define BULLION_1_Y						0x0156

#define BOTTLE_1_X						0x0720 
#define BOTTLE_1_Y						0x0280

#define BOTTLE_2_FRONT_X				0x05DC  
#define BOTTLE_2_FRONT_Y				0x0800

#define BOTTLE_2_X						0x0730 
#define BOTTLE_2_Y						0x076C

#define CD_TAKE_X						0x05A8
#define CD_TAKE_Y						0x02C8

#define DROP_ZONE_1_X					GAMEBOARD_MIDDLE_WIDTH
#define DROP_ZONE_1_Y					0x00D5

#define BULLION_LEFT_AND_RIGHT_Y		0x05A0

#define BULLION_RIGHT_1_X				X_LINTEL_RIGHT
#define BULLION_RIGHT_1_Y				BULLION_LEFT_AND_RIGHT_Y

#define BULLION_LEFT_1_X				X_LINTEL_LEFT
#define BULLION_LEFT_1_Y				BULLION_LEFT_AND_RIGHT_Y

#define FRONT_OF_MAP_LOCATION_X			0x01C2
#define FRONT_OF_MAP_LOCATION_Y			GAMEBOARD_MIDDLE_HEIGHT

#define BULLION_MIDDLE_2_X				GAMEBOARD_MIDDLE_WIDTH
#define BULLION_MIDDLE_2_Y				0x08E8


// GAINS

#define BULLION_GAIN			3
#define BOTTLE_GAIN				3
#define CD_4_GAIN				4
#define BULLION_GAIN			3
#define OPPONENT_CD_GAIN		3

// COST : between 0 and 255

// -> General
#define START_AREA_TO_BULLION_1_COST							100
#define BULLION_1_TO_BOTTLE_1_COST								80
#define BOTTLE_1_TO_BOTTLE_2_FRONT_COST							80
#define BOTTLE_2_FRONT_TO_BOTTLE_2_COST							40
#define BOTTLE_2_TO_CD_COST										50
#define CD_TO_DROP_ZONE_1_COST									100
#define START_AREA_TO_FRONT_OF_MAP_COST							150


// -> Bullion Right 1
#define BULLION_1_TO_BULLION_RIGHT_1_COST						100
#define DROP_ZONE_1_TO_BULLION_RIGHT_1_COST						100

// -> Bullion Left 1
#define DROP_ZONE_1_TO_BULLION_LEFT_1_COST						100

#define AFTER_BULLION_LEFT_1_TO_START_AREA_CENTER_COST			50
#define START_AREA_CENTER_TO_START_AREA_DROP_ZONE_COST			80

// -> Opponent CD
#define FRONT_OF_MAP_TO_BULLION_MIDDLE_2_COST					50
#define BULLION_MIDDLE_2_TO_BOTTLE_2_FRONT_COST					40
#define BOTTLE_2_FRONT_TO_DROP_ZONE_1_COST						150


// SPEED FACTOR : between 0 and 15
#define START_AREA_TO_BULLION_1_SPEED_FACTOR					MOTION_SPEED_FACTOR_MAX
#define BULLION_1_TO_BOTTLE_1_SPEED_FACTOR						MOTION_SPEED_FACTOR_MAX
#define BOTTLE_1_TO_BOTTLE_2_SPEED_FACTOR						MOTION_SPEED_FACTOR_HIGH		
#define BOTTLE_2_TO_CD_SPEED_FACTOR								MOTION_SPEED_FACTOR_LOW
#define CD_TO_DROP_ZONE_1_SPEED_FACTOR							MOTION_SPEED_FACTOR_HIGH
#define	START_AREA_TO_FRONT_OF_MAP_SPEED_FACTOR					MOTION_SPEED_FACTOR_MAX

// -> Bullion Right 1
#define BULLION_1_TO_BULLION_RIGHT_1_SPEED_FACTOR				MOTION_SPEED_FACTOR_NORMAL
#define DROP_ZONE_1_TO_BULLION_RIGHT_1_SPEED_FACTOR				MOTION_SPEED_FACTOR_NORMAL

// -> Bullion Left 1
#define DROP_ZONE_1_TO_BULLION_LEFT_1_SPEED_FACTOR				MOTION_SPEED_FACTOR_NORMAL

// -> Opponent CD
#define FRONT_OF_MAP_TO_BULLION_MIDDLE_2_SPEED_FACTOR			MOTION_SPEED_FACTOR_NORMAL
#define BULLION_MIDDLE_2_TO_BOTTLE_2_FRONT_SPEED_FACTOR			MOTION_SPEED_FACTOR_NORMAL
#define BOTTLE_2_FRONT_TO_DROP_ZONE_1_SPEED_FACTOR				MOTION_SPEED_FACTOR_MAX

// ACCELERATION FACTOR : between 0 and 15
// -> General
#define START_AREA_TO_BULLION_1_ACCELERATION_FACTOR				MOTION_ACCELERATION_FACTOR_MAX
#define BULLION_1_TO_BOTTLE_1_ACCELERATION_FACTOR				MOTION_ACCELERATION_FACTOR_MAX
#define BOTTLE_1_TO_BOTTLE_2_ACCELERATION_FACTOR				MOTION_ACCELERATION_FACTOR_HIGH		
#define BOTTLE_2_TO_CD_ACCELERATION_FACTOR						MOTION_ACCELERATION_FACTOR_LOW
#define CD_TO_DROP_ZONE_1_ACCELERATION_FACTOR					MOTION_ACCELERATION_FACTOR_HIGH
#define START_AREA_TO_FRONT_OF_MAP_ACCELERATION_FACTOR			MOTION_ACCELERATION_FACTOR_MAX

// -> Bullion Right 1
#define BULLION_1_TO_BULLION_RIGHT_1_ACCELERATION_FACTOR		MOTION_ACCELERATION_FACTOR_HIGH
#define DROP_ZONE_1_TO_BULLION_RIGHT_1_ACCELERATION_FACTOR		MOTION_ACCELERATION_FACTOR_HIGH

// -> Bullion Left 1
#define DROP_ZONE_1_TO_BULLION_LEFT_1_ACCELERATION_FACTOR		MOTION_ACCELERATION_FACTOR_HIGH

// -> Opponent CD
#define FRONT_OF_MAP_TO_BULLION_MIDDLE_2_ACCELERATION_FACTOR	MOTION_ACCELERATION_FACTOR_NORMAL
#define BULLION_MIDDLE_2_TO_BOTTLE_2_FRONT_ACCELERATION_FACTOR	MOTION_ACCELERATION_FACTOR_NORMAL
#define BOTTLE_2_FRONT_TO_DROP_ZONE_1_ACCELERATION_FACTOR		MOTION_ACCELERATION_FACTOR_MAX

/**
 * Init all elements for 2012.
 */
void initStrategy2012(int strategyIndex);

/**
 * Print 
 */
void printStrategyAllDatas(OutputStream* outputStream);

/**
 * Define the color and update strategy.
 */
void setColor(TEAM_COLOR color);

#endif
